# action.yaml
name: 'Python Black Check'
description: 'Customisable GitHub action to use black to check Python code in your repository'
branding:
  icon: 'code'
  color: 'black'
inputs:
  path:
    description: 'File or directory to run black on.'
    required: false
    default: '.'
  line-length:
    description: 'The number of characters allowed per line.'
    required: false
    default: '81'
  include:
    description: 'A regular expression that matches files and directories that should be included on recursive searches.'
    required: false
    default: '\.pyi?$'
  exclude:
    description: 'A regular expression that matches files and directories that should be excluded on recursive searches.'
    required: false
    default: '/(\.direnv|\.eggs|\.git|\.hg|\.mypy_cache|\.nox|\.tox|\.venv|\.svn|_build|buck-out|build|dist)/'
outputs:
  output:
    description: 'The output of black.'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.line-length }}
    - ${{ inputs.path }}
    - ${{ inputs.include }}
    - ${{ inputs.exclude }}
